name: CI

on:
  push:
    branches: [ "main" ]


jobs:

  btd:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Building code..."
        
      - name: Test
        run: cd nothinghere

      - name: Deploy
        run: echo "Deploying code..."
